### ISSUE TITLE
Look in the appdata folder for custom instructions/themes

### ISSUE THREAD

**Issue by machinewrapped** [machinewrapped/gpt-subtrans#111]
To make it easier for people to keep custom instructions or themes when upgrading or reinstalling, we should support loading them from the appdata folder instead of the installation folder.

**Comment by machinewrapped** [comment]
Been thinking about this some more. The problem is making sure all the instructions, default and custom, are available in the drop-down - and ideally when people click "Load Subtitles". Either needs to a) copy the default instructions to appdata or b) copy custom instructions to the app directory.

I guess a) will be more straightforward, but need to update the instruction files when a new version is downloaded/installed. Easy enough to check when there's a version change, I guess.

**Comment by Nikola611** [comment]
I'd like to tackle this issue

**Comment by Nikola611** [comment]
Nvm I don't know if I can figure it out, when I try to take instructions from appdata and merge it with the default instructions, I just get the default instructions twice.

**Comment by machinewrapped** [comment]
Hey, don't worry about it - thanks for trying! I think it is more complicated than it sounds. I'll take another look at it one of these days.

**Comment by machinewrapped** [comment]
Implemented in https://github.com/machinewrapped/gpt-subtrans/commit/0ddc531f80925e77d7dc924ffafc96a2041c492d

Thanks for your efforts - your approach was helpful in clarifying how I thought about the problem, which made it easier to figure out a good solution.
