### ISSUE TITLE
Retranslate Lines

### ISSUE THREAD

**Issue by fenixpsicologia** [machinewrapped/gpt-subtrans#112]
I would suggest that the interface has an option to retranslate just one dialog. Currently there is something like this, but from what I've seen it doesn't work or ends up translating several dialogues.

**Comment by machinewrapped** [comment]
"Translate Selection" currently operates at the batch/scene level - I've been meaning to support retranslating individual lines for ages (it will still send the full batch to the translator so that it has the context, but pick out the selected lines from the translation) - thanks for the reminder!

**Comment by machinewrapped** [comment]
A preliminary version of this is implemented in v0.5.6. It needs more testing so it's set as a pre-release version for now.

https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.5.6

If you get chance to try it out let me know if you encounter any problems :-)

**Comment by machinewrapped** [comment]
This has now been incorporated into the latest official release, along with a further visual overhaul.

https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.5.8

![image](https://github.com/machinewrapped/gpt-subtrans/assets/10140676/2b25fde9-e0c9-43ba-9da8-fa919076f22f)

Let me know what you think in the discussion for the release.
https://github.com/machinewrapped/gpt-subtrans/discussions/119
