### ISSUE TITLE
Error in Installation using Main Branch

### ISSUE THREAD

**Issue by bebetoalves** [machinewrapped/gpt-subtrans#116]
I'm facing this issue after installing it following the script `./install.sh`. I tested it on Windows and the issue was the same.

Python version: 3.11.7

```bash
Traceback (most recent call last):
  File "/home/alves/Downloads/gpt-subtrans/gui-subtrans.py", line 9, in <module>
    from GUI.MainWindow import MainWindow
  File "/home/alves/Downloads/gpt-subtrans/GUI/MainWindow.py", line 200
    logging.debug(f"A {type(command).__name__} command {"succeeded" if success else "failed"})")
                                                         ^^^^^^^^^
SyntaxError: f-string: expecting '}'
```

Steps to reproduce:

1. Install via `install.sh` or `install.bat`
2. Run the `gui-subtrans.sh` script

**Comment by machinewrapped** [comment]
Thanks for the report, it's strange as that line hasn't changed in a very long time. I couldn't reproduce the issue locally, I wonder if it is locale dependent. I've updated it to use different quotes for the inner strings anyway, which ought to solve the error. Can you update to latest and try again? You shouldn't need to rerun the install script or anything.

**Comment by bebetoalves** [comment]
Fixed. Thank you!
