### ISSUE TITLE
Gemini ignores target language and translates to English.

### ISSUE THREAD

**Issue by xpufx** [machinewrapped/gpt-subtrans#135]
I am trying to use Gemini to translate from Italian to another language. But it always translates parts of scenes into English. I cannot retranslate those bits because the GUI crashes (as in my other bug report) and I don't know if it's possible to do it with the CLI. 

Does this have something to do with the prompts being in English? I tried to add some wording like "always translate to the target language" etc but that didn't make a difference. As far as I can tell this does not happen with GPT4. Any suggestions?

**Comment by machinewrapped** [comment]
Hmm, I don't have an immediate answer I'm afraid - I haven't encountered it in my testing.

It is definitely possible that the instructions being in English bias the model towards "respond in English". Try translating just the prompt to Italian, see if that's enough to encourage it to stay on track. Leave the tags in English though as they're replaced (maybe I need to think of a more language-agnostic way to do that!).

"Per favore, traduci questi sottotitoli [ for movie][ to language]"
