### ISSUE TITLE
Strange GUI Behavior

### ISSUE THREAD

**Issue by fenixpsicologia** [machinewrapped/gpt-subtrans#147]
When clicking on a single line to try to translate it, I notice from the logs console that the translation is done but it is also trying exhaustively to translate the other scenes even without having asked.

**Comment by machinewrapped** [comment]
Ooh, so it is - just the batches in the same scene as the line though, I think? I'll push a fix tomorrow.

**Comment by machinewrapped** [comment]
I've fixed this and updated the v0.6.4 release.

**Comment by fenixpsicologia** [comment]
Thank you, solved.
