### ISSUE TITLE
Validation error when subtitle dialog has a hashtag

### ISSUE THREAD

**Issue by fenixpsicologia** [machinewrapped/gpt-subtrans#163]
When trying to translate a subtitle that contains # in the dialogues, the translation validation fails.

1. Use a subtitle that has a dialogue with #, typically accompanied by a number, for example: # 1
2. Try to translate using some provider (I used Claude)
3. Observe the logs

**Comment by machinewrapped** [comment]
Thanks for the report, I'll take a look - shouldn't be too hard to fix!

**Comment by machinewrapped** [comment]
That wasn't too hard to fix :)

https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.6.8

(I'll upload a macOS version tomorrow if you need it)

**Comment by machinewrapped** [comment]
Closing as fixed
