### ISSUE TITLE
gui-subtrans on Windows can't load SRT file

### ISSUE THREAD

**Issue by zhoukuncheng** [machinewrapped/gpt-subtrans#171]
: `Error initialising project : Value '' not found in []`

: 
```
INFO: Initialising 
INFO: Loaded settings from C:\Users\jack\AppData\Roaming\MachineWrapped\GPTSubtrans\settings.json
INFO: Loading stylesheet from C:\tools\gui-subtrans\_internal\\subtrans.qss
INFO: GUI-Subtrans v0.7.0
INFO:  to C:\Users\jack\AppData\Roaming\MachineWrapped\GPTSubtrans\gui-subtrans.log
INFO: Project file C:\Users\jack\Downloads\You need $500. How should you get it.en-US.subtrans does not exist
ERROR: Error initialising project settings: Value '' not found in []
```

 file: a random VTT subtitle downloaded from YouTube and converted to SRT:

[You need $500. How should you get it.en-US.srt.zip](https://github.com/machinewrapped/gpt-subtrans/files/15277028/You.need.500.How.should.you.get.it.en-US.srt.zip)

Version:   v0.7.1

**Comment by machinewrapped** [comment]
It doesn't seem to be a problem with the SRT file, it looks like a configuration issue. 

Which provider are you using? Did you run the install script for it?

**Comment by machinewrapped** [comment]
Try v0.7.3, I added some extra handling in the new project settings dialog, which might at least provide more information about what the problem is. https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.7.3

**Comment by machinewrapped** [comment]
I found the problem - it did happen if the provider is not configured correctly (e.g. an invalid API key). Should be fixed in v0.7.4.
https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.7.4

You will still need to configure the provider before you can translate, but at least it should tell you that instead of crashing :-)

**Comment by zhoukuncheng** [comment]
Thanks. In v0.7.4, it works now. 

I am using `gui-subtrans` with a local model (`wangshenzhi/llama3-8b-chinese-chat-ollama-q4:latest`) with Ollama, so I don’t need to configure the API key.

**Comment by machinewrapped** [comment]
Ah, good luck - I haven't had good results with local models so far, let me
know how it goes!

**Comment by zhoukuncheng** [comment]
With a fine-tuned llama3-8b model, I see the translation results are acceptable. For example, wangshenzhi/llama3-8b-chinese-chat-ollama-q4:latest for English to Chinese translation.
