### ISSUE TITLE
Suggestion: Retranslate Entire Subtitle

### ISSUE THREAD

**Issue by fenixpsicologia** [machinewrapped/gpt-subtrans#183]
I'd like to make a suggestion: When I want to retranslate the entire document again (whether using the same provider or not), I have to click on each section and request to translate that section. There could be a button to clear the entire translation or a button to retranslate everything.

**Comment by machinewrapped** [comment]
You can press Ctrl+A to select all and then "Translate Selection" as a faster way to do this (or select all the individual scenes you want to retranslate).

I'll add a Shift key modifier to the Start Translating / Fast Translation buttons on the toolbar too though, which will make them retranslate scenes and batches that are already translated.

Question: would you want it to keep existing scene/batch summaries when retranslating them? There is a legacy option to do that, but it can only be accessed via the command line at the moment. It could be useful if you've hand-edited them to make them more accurate?

**Comment by fenixpsicologia** [comment]
> You can press Ctrl+A to select all and then "Translate Selection" as a faster way to do this (or select all the individual scenes you want to retranslate).
> 
> I'll add a Shift key modifier to the Start Translating / Fast Translation buttons on the toolbar too though, which will make them retranslate scenes and batches that are already translated.
> 
> Question: would you want it to keep existing scene/batch summaries when retranslating them? There is a legacy option to do that, but it can only be accessed via the command line at the moment. It could be useful if you've hand-edited them to make them more accurate?

I don't think I would edit it; based on my experience, the summaries are usually correct with the scene.

**Comment by machinewrapped** [comment]
Now supported in v0.8.2 - Shift+Click on Translate or Fast Translate to restart translation from the beginning. The summaries will be updated by the translation at the moment, but I'll change it in a future release so that they are left unchanged.

**Comment by peterkizumaki** [comment]
![Auto-translate-Error](https://github.com/machinewrapped/gpt-subtrans/assets/147496138/c12991b2-42c5-4637-88b4-67676484b5b2)
Hi,
I could not use the Autro-translate and got this error.
I am so sorry that I do not know wherever to ask for the solution. 
Please help to advise how to fix this error.

Thanks so much!!

**Comment by machinewrapped** [comment]
@peterkizumaki  probably better to ask here 😄  https://github.com/SubtitleEdit/subtitleedit/issues

**Comment by peterkizumaki** [comment]
Thanks so much! I fixed it :))
