### ISSUE TITLE
Manual translation.

### ISSUE THREAD

**Issue by RistoRoosipuu** [machinewrapped/gpt-subtrans#185]
I have been experiencing an odd issue lately.

I download a subtitle file, I fix it, maybe remove some lines and reorder line numbering using SubtitleEdit.

Then I start translating each section using GUI but sometimes I manually translate some sections since its only a few lines.

The .subtrans contains all my edits and when I click save, it says that it saves them to the actual .srt file but when I open them, they are always missing.

This is using 0.81.

**Comment by machinewrapped** [comment]
Thanks for the report, I'll take a look!

**Comment by RistoRoosipuu** [comment]
I think its better now, tried a fresh subtitle file. I'll run a few more tests just in case over the next few days.
