### ISSUE TITLE
[How To] exe installation on windows, server adress

### ISSUE THREAD

**Issue by Maitresinh** [machinewrapped/gpt-subtrans#189]
I'm trying to install GPT-subtrans in windows, in order to make tests.
I've entered my Api key on a .en file in the root. But i have no clue about how to find the server adress. Is it my ip adresse ?

![Capture d’écran 2024-07-04 101513](https://github.com/machinewrapped/gpt-subtrans/assets/37817197/32412e1d-45e6-44ff-a737-839616b0aea0)

**Comment by machinewrapped** [comment]
Hi, it looks like you haven't installed any providers so only Local Server is available. If you really do want to use a local server, e.g. LLM Studio or Ollama, that's OK - you'll need to get the server running first though, and it should give you an address to connect to (e.g. `http://localhost:1234`) - you're unlikely to need an API Key.

If you actually want to use a third party service though, e.g. OpenAI, the easiest option is to run one of the install-xxx scripts, e.g. `install-openai.bat`. It will install the required libraries and prompt you for an API key and URL (leave it blank to use the official OpenAI server), and write the .env file. You should then be ready to run! You can install multiple providers if necessary.

Check the README for more details.
https://github.com/machinewrapped/gpt-subtrans?tab=readme-ov-file#installing-from-source

Step 1 should be all most users need.

**Comment by Maitresinh** [comment]
thanks.

I installed the .bat.
Then runing the GUI and change the parameters here
![Capture d’écran 2024-07-04 181200](https://github.com/machinewrapped/gpt-subtrans/assets/37817197/47a8dcfe-02af-4beb-8d13-6268613c552c)

And got an error : 

INFO: Starting single threaded translation
INFO: Translating scene number 1
INFO: Translating with local server at /v1/chat/completions
ERROR: Error translating scene 1: Unexpected error communicating with server
ERROR: Unrecoverable error in TranslateSceneCommand
INFO: HTTP Request: GET https://api.openai.com/v1/models "HTTP/1.1 200 OK"

or in the GUI
Thursday, 18:10:04 - Translating scene number 1
Thursday, 18:10:04 - Translating with local server at /v1/chat/completions
Thursday, 18:10:04 - Error translating scene 1: Unexpected error communicating with server
Thursday, 18:10:04 - Unrecoverable error in TranslateSceneCommand
Thursday, 18:11:20 - HTTP Request: GET https://api.openai.com/v1/models "HTTP/1.1 200 OK"
Thursday, 18:13:17 - Settings updated

**Comment by machinewrapped** [comment]
The settings look right, but according to the logs it's still trying to translate with a local server. 

If you already created the project it will remember the provider that was selected when the project was created. You can change it in the GUI by opening the project properties (hamburger icon on the side toolbar).
![image](https://github.com/machinewrapped/gpt-subtrans/assets/10140676/41d6947d-d484-4b4c-a8e2-11577e544cff)

Or just delete the .subtrans file and start a new project, since I guess you don't have anything translated yet to lose :-)

**Comment by Maitresinh** [comment]
Ok. Seems to work. Almost

Friday, 14:40:51 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
Friday, 14:40:51 - Retrying request to /chat/completions in 1.841547 seconds
Friday, 14:40:53 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
Friday, 14:40:53 - Error translating scene 1: OpenAI account quota reached, please upgrade your plan
Friday, 14:40:53 - Unrecoverable error in TranslateSceneCommand

I will have to wait....

Thanks anyway
