### ISSUE TITLE
GUI with python 3.8

### ISSUE THREAD

**Issue by cjhonlyone** [machinewrapped/gpt-subtrans#19]
PySide6              6.5.0
PySide6-Addons       6.5.0
PySide6-Essentials   6.5.0
shiboken6            6.5.0

PySide6/__init__.py: Unable to import Shiboken from D:\FastChat\gpt-subtrans, C:\Users\F520-CJH\AppData\Local\Programs\Python\Python38\python38.zip, C:\Users\F520-CJH\AppData\Local\Programs\Python\Python38\DLLs, C:\Users\F520-CJH\AppData\Local\Programs\Python\Python38\lib, C:\Users\F520-CJH\AppData\Local\Programs\Python\Python38, D:\FastChat\fastchatvenv, D:\FastChat\fastchatvenv\lib\site-packages
Traceback (most recent call last):
  File ".\gui-subtrans.py", line 6, in <module>
    from PySide6.QtWidgets import QApplication
  File "D:\FastChat\fastchatvenv\lib\site-packages\PySide6\__init__.py", line 124, in <module>
    _setupQtDirectories()
  File "D:\FastChat\fastchatvenv\lib\site-packages\PySide6\__init__.py", line 64, in _setupQtDirectories
    from shiboken6 import Shiboken
  File "D:\FastChat\fastchatvenv\lib\site-packages\shiboken6\__init__.py", line 27, in <module>
    from shiboken6.Shiboken import *
ImportError: DLL load failed while importing Shiboken: 找不到指定的程序。

Can you describe more about your running environment?

**Comment by machinewrapped** [comment]
I'm using Python 3.11 - there have been issues reported with older Python versions, so it's probably best to be as up-to-date as possible. If you use one of the pre-packaged builds it includes the Python interpreter and the libraries as they were when the package was built, which should avoid any compatibility problems.
