### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by ivaniclixx** [machinewrapped/gpt-subtrans#32]
python gpt-subtrans.py ../../Downloads/subtitles.es.srt --target_language English

INFO: Translating 196 subtitles from ../../Downloads/subtitles.es.srt
INFO: Translating 196 lines in 1 scenes
WARNING: Unable to match 24 lines with a source line
WARNING: Scene 1 batch 1 failed validation, requesting retranslation

**Comment by ivaniclixx** [comment]
I think I localized the problem. The newlines for the file were in DOS format, running from Linux, caused some confusion to Python

**Comment by machinewrapped** [comment]
Newlines are the gift that keeps on giving! I'll see if there's something I can do to normalise the input.

**Comment by machinewrapped** [comment]
OK, it's a bit of a shot in the dark but I discovered there's an option to normalise newlines when reading a file in Python, so I've enabled it for subtitles and project files. It doesn't seem to make things worse, at least on Windows - hopefully it will make things better!
