### ISSUE TITLE
GUI related issues

### ISSUE THREAD

**Issue by AChangAZha** [machinewrapped/gpt-subtrans#33]
When this checkbox is checked, then click the Start button. The checkbox will be unchecked.
![Snipaste_2023-06-05_21-32-56](https://github.com/machinewrapped/gpt-subtrans/assets/80208659/0a8e8314-1278-4281-8417-3cb6868df959)
I've tried it several times and it's the same. But in the end, except the check box is also unchecked, the content of the Substitutions option is also cleared, and at this time `match partial words` will work.😂
Then, I closed the program and reopened it, and loaded the same subtitle file. It will show: `Project file loaded, saving backup copy`. No options can be modified at this time. 
![Snipaste_2023-06-05_21-44-10](https://github.com/machinewrapped/gpt-subtrans/assets/80208659/da8caa31-0f61-428b-b144-32608eac3fcd)
When trying to open other subtitles that don't have a project file. will display: `Project file xxx.subtrans does not exist`.
I had to delete the files in `C:\Users\user\AppData\Roaming\MachineWrapped\GPTSubtrans` to get back to normal.

**Comment by AChangAZha** [comment]
more details
![Snipaste_2023-06-05_21-50-17](https://github.com/machinewrapped/gpt-subtrans/assets/80208659/b7c747b4-105c-43b0-a1fe-46dcf756beed)

**Comment by machinewrapped** [comment]
Well, we can file that bug under "How the hell did I miss that? 😅  Fixed in 0.2.5.

**Comment by AChangAZha** [comment]
Thanks for your hard work!
