### ISSUE TITLE
WARNING: Scene 1 batch 1 failed validation, requesting retranslation

### ISSUE THREAD

**Issue by chen-rn** [machinewrapped/gpt-subtrans#38]
```
Terminal:
INFO: Translating 57 subtitles from transcript.srt
INFO: Translating 57 lines in 1 scenes
WARNING: Unable to match 30 lines with a source line
WARNING: Scene 1 batch 1 failed validation, requesting retranslation
ERROR: Retranslation request did not produce a useful result
WARNING: Retranslation request did not fix problems:
I apologize for the mistake. Here is the corrected translation:

#1
原文>
So, uh, I guess Reddit's over? It's weird. The last couple days of Google searching things,
翻訳>
那么，嗯，我猜Reddit结束了？很奇怪。过去几天在谷歌上搜索东西，点击链接，然后出现私人回复的subreddit感觉很奇怪，

#2
原文>
clicking links, and having a subreddit is private response come up has been strange,
翻訳>
但这确实帮助我反思Reddit对我的日常工作和生活的重要性。从调试代码到修复视频编辑中的奇怪伪影，甚至是获取新旧事物的意见。我依赖Reddit查找信息和获取人类对事物的意见的程度是巨大的。而且似乎AI公司也有同感，因为绝大多数AI都在Reddit上进行了一定程度的训练。看来他们想试图从中赚钱。不幸的是，与Reddit所做的大多数事情一样，他们不知道自己在做什么。Reddit最近宣布了对API的更改，应用程序协议接口，是外部事物访问Reddit的简写。Reddit的API对于许多事情都是必不可少的。显然，它被用于训练AI机器人，但它也用于使Reddit可用，无论是为需要屏幕阅读器支持的人提供辅助工具，还是为了一个真正有效的好移动应用程序。当然，还有大规模的安全工具。Reddit API对于许多人的工作至关重要。对于仅仅使用Reddit，我个人在浏览Reddit时从不使用计算机。我在手机上使用Narwhal应用程序。Narwhal和Apollo是Reddit的两个主要移动应用程序。我知道Reddit很有趣也很受欢迎。似乎所有三个应用程序都将不得不关闭他们的大门，因为Reddit的API定价是荒谬的。Apollo的使用完全在Reddit推荐的API使用限制范围内。而且主要开发人员实际上与Reddit保持联系，并且在与他们沟通时做得非常好，让他们知道何时出现错误，何时受到过多打击，以及保持Reddit API处于良好状态。他的奖励是被指控敲诈勒索。说真的，作为一位CEO，我永远不会理解Spez如何应对所有这些问题。天哪，我只是感到恐惧。真的，看到一位CEO选择追求为使他的产品更好而努力工作的个人社区成员，这真是太恶心了。Apollo不是因为开发人员讨厌Reddit而制作的。Apollo不是因为开发人员想从Reddit赚钱而制作的。Apollo是因为开发人员想在iOS上变得更好，喜欢Reddit并想要更好的Reddit体验。他制作了一个应用程序，赢得了无数的设计奖项，甚至直接来自苹果。事实上，在关闭之前，他在WWDC，苹果的会议中被提到。所以我可以看到我的Apollo for Reddit。在同一24小时窗口内，在苹果的会议上展示制作出令人难以置信的应用程序，然后立即被指控敲诈勒索，这是超现实的。

INFO: Scene 1 batch 1: 0 lines and 30 untranslated.
INFO: Summary: A discussion about recent changes to Reddit's API and how it affects users and developers.
INFO: Scene 1 batch 2: 27 lines and 0 untranslated.
INFO: Summary: A discussion about recent changes to Reddit's API and how it affects users and developers.
INFO: Saving translation to transcript-GPT.srt
INFO: Successfully translated 27 lines!
WARNING: Failed to translate 30 lines:
INFO: Untranslated > 1. So, uh, I guess Reddit's over? It's weird. The last couple days of Google searching things,
INFO: Untranslated > 2. clicking links, and having a subreddit is private response come up has been strange,
INFO: Untranslated > 3. but it's really helped me reflect on how important Reddit is to my everyday work and life. Everything
INFO: Untranslated > 4. from debugging code stuff to fixing weird artifacts in my video edits to just getting
INFO: Untranslated > 5. opinions on some new thing that shipped or even old things. The amount I rely on Reddit to find
INFO: Untranslated > 6. information and get humans opinions on things is massive. And it seems like the AI companies felt
INFO: Untranslated > 7. the same way because the vast majority of AI is trained on Reddit some amount. It seems like they
INFO: Untranslated > 8. want to try and make money off that. Sadly, as with most of the things Reddit does, they had no
INFO: Untranslated > 9. idea what they were doing. Reddit recently announced changes to the API, application
INFO: Untranslated > 10. protocol interface, the shorthand for how external things access Reddit. Reddit's API is essential
INFO: Untranslated > 11. for a lot of things. Obviously it's being used to train robots for AI stuff, but it's also used to
INFO: Untranslated > 12. make Reddit usable, be it accessibility tools for people who need screen reader support or just a
INFO: Untranslated > 13. good mobile app that actually works. And obviously safety tools in mass. The Reddit API is essential
INFO: Untranslated > 14. for the work that many do. And for just using Reddit, I personally, when I browse Reddit,
INFO: Untranslated > 15. never do it on a computer. I use the Narwhal app on my phone. Narwhal and Apollo are the two
INFO: Untranslated > 16. go-to mobile apps for Reddit. I know Reddit is fun is also pretty popular. And it seems like all
INFO: Untranslated > 17. three will have to shut their doors down because Reddit's pricing for their API is absurd. Apollo
INFO: Untranslated > 18. was well within the limits of what Reddit recommended for their API usage. And the lead
INFO: Untranslated > 19. developer was actually in touch with Reddit and did a great job communicating with them,
INFO: Untranslated > 20. letting them know when there were bugs, when things were getting hit too much, and just keeping
INFO: Untranslated > 21. the Reddit API in a good state. His reward for this work was getting accused of blackmail.
INFO: Untranslated > 22. Seriously, as a fellow CEO, I will never understand how Spez has responded to all of this.
INFO: Untranslated > 23. God, I just I'm horrified. Truly, it is just disgusting to see a CEO choosing to go after
INFO: Untranslated > 24. individual community members who are working hard to make his product better. Apollo wasn't made
INFO: Untranslated > 25. because the developer hates Reddit. Apollo wasn't made because the developer wanted to make money
INFO: Untranslated > 26. off Reddit. Apollo was made because a developer wanted to get better at iOS, loved Reddit and
INFO: Untranslated > 27. wanted a better Reddit experience. And he made an app that's won countless design awards, even from
INFO: Untranslated > 28. Apple directly. In fact, right before the shutdown, he got mentioned in WWDC, Apple's conference.
INFO: Untranslated > 29. So I can see my Apollo for Reddit. It is surreal to within the same 24 hour window, get shown off
INFO: Untranslated > 30. at Apple's conference for making an incredible app and then immediately get accused of blackmail
INFO: Saving translation to transcript-GPT.srt
```

Any idea what this is caused by?
I copied the PySubtitleGPT Folder and just ran gpt-subtrans.py.

**Comment by chen-rn** [comment]
Note, it didn't work with gpt-3.5-turbo but did execute successfully with gpt-4-0613.

**Comment by machinewrapped** [comment]
I would guess it's because the transcript isn't broken up into sentences, so to make sense of it GPT has to merge lines, ignoring the breaks, then gpt-3 at least isn't smart enough to split them up again.

It's interesting that gpt-4 is able to handle it - I still don't have API access (AFAIK) but I always suspected it would be much less prone to doing things like this!

If you wanted it to work with GPT-3 the best option by far would be to reformat the source text into complete sentences, but that is obviously going to be a lot of work. The alternative would be to send smaller batches for translation... given that every line in the transcription seems to be long, I'd guess 10-15 lines per batch would be more manageable for GPT-3, though it would be best to avoid batches starting or ending mid-sentence.

Sounds like "use GPT-4" is the best answer though :-)

**Comment by chen-rn** [comment]
Interestingly, this works with `gpt-3.5-turbo-0613` but not `gpt-3.5-turbo`! I think in a ~week, 3.5-turbo will point to the 0613 version so hopefully things will be better!

> Re:I'd guess 10-15 lines per batch would be more manageable for GPT-3.
I tried with MAX_BATCH_SIZE=10, but it failed on the second batch of 10 lines.

I got my transcript from Whisper, hopefully this is an edge case that's fully covered by the new gpt-3.5-turbo-0613 and gpt-4!

**_Side note:**
`parser.add_argument('--maxlines', type=int, default=None, help="Maximum number of batches to process")`
Max lines's description says max number of batches to process. Is that a typo or is maxline the max number of batches?_

**Comment by chen-rn** [comment]
Do you think the new function calling feature be used in this case to help?

**Comment by machinewrapped** [comment]
Oh, that's a typo - maxlines will stop processing the file after a certain number of lines (it was batches once upon a time).

If the latest 3.5 model already handles this case better than that is good news - surprising though, I wonder if it's had GPT-4 training it!

I can't think of a use for the function call feature at the moment, anything that I could offer as a function to GPT could probably be done automatically by pre-/post-processing the subtitles. I'm open to suggestions though!

It would be a good addition to have a function to join/split lines on punctuation and scale the timings... it would be rough without matching it to the audio/video, but it should at least produce more coherent translations. Actually I wonder if Subtitle Edit already has something for that?

**Comment by chen-rn** [comment]
> I can't think of a use for the function call feature at the moment

Yea I struggled to think of low hanging fruits using functions as well.
I was thinking maybe it can enforce the number of "lines" in the output?(or the number of "segments", I'm not sure if that's what a "line" is in your code, or if it's simply a "\n")

ie.
if the input has 10 lines, the output _must_ also have 10 lines.
In the error case above, the input had a batch size of 30, but the output only contained 2 lines.

Not too sure though, haven't looked too deep into it!

**Comment by machinewrapped** [comment]
That is one of the validations that is run on the response (enforce_line_parity), if it doesn't find a matching translation for each source line it points out the problem and requests a retranslation - usually that's enough for GPT to fix the error, but in your case the retranslation failed validation as well.

**Comment by henriquepiresmartins** [comment]
Guys, I apologize, but this was the only space I found to ask a question: would you happen to know if the translation speed is faster in the paid API?
I would like to congratulate everyone involved in this project in advance.

**Comment by machinewrapped** [comment]
Hi, and thanks :-)

The translation speed is definitely noticeably faster with a paid API key, free trial accounts are severely rate limited - I believe there's still a cap applied for the first few days after registering a payment method too, but after that it's much less restricted.

It's still not "fast fast" though, it can take 10-60 to get a response for each batch request, with the time increasing as the batch size increases. I usually expect to be waiting 20-40 minutes for a full movie, depending on how dense the subtitles are.

You can get much faster speeds by translating scenes simultaneously though, which is what the "Fast Forward" button on the toolbar does. This only works with a paid API key, as the free trial rate limit is too low to be worth sending more than one request at a time. There is a possible cost to translation quality, since each scene won't be able to provide the summary of the previous scene as context - but the difference it makes is usually not that significant.

Feel free to open a new issue if you have any more questions!

**Comment by henriquepiresmartins** [comment]
> Hi, and thanks :-)
> 
> The translation speed is definitely noticeably faster with a paid API key, free trial accounts are severely rate limited - I believe there's still a cap applied for the first few days after registering a payment method too, but after that it's much less restricted.
> 
> It's still not "fast fast" though, it can take 10-60 to get a response for each batch request, with the time increasing as the batch size increases. I usually expect to be waiting 20-40 minutes for a full movie, depending on how dense the subtitles are.
> 
> You can get much faster speeds by translating scenes simultaneously though, which is what the "Fast Forward" button on the toolbar does. This only works with a paid API key, as the free trial rate limit is too low to be worth sending more than one request at a time. There is a possible cost to translation quality, since each scene won't be able to provide the summary of the previous scene as context - but the difference it makes is usually not that significant.
> 
> Feel free to open a new issue if you have any more questions!

Thank you for the clarification.
Another thing that concerns me is the cost of translations. I know it may not apply to all examples, but on average, how much did it cost you to translate a movie?

**Comment by machinewrapped** [comment]
Less than $0.5, probably nearer $0.2 in most cases.
