### ISSUE TITLE
Output the original text and translation

### ISSUE THREAD

**Issue by cddqssc** [machinewrapped/gpt-subtrans#39]
Great application! I want to know if it's possible to output the original text and translation together to an SRT file?

**Comment by machinewrapped** [comment]
Thanks! That wouldn't be difficult, I just need to think about the UI for it. Would you expect something like 

Original Text On Top
Translated Text Underneath

for each line?

**Comment by cddqssc** [comment]
"Original Text On Top
Translated Text Underneath，for each line"
totally agree!

**Comment by machinewrapped** [comment]
I am working on this by the way - sorry for the delay!

**Comment by machinewrapped** [comment]
I _finally_ finished this, it's in the latest release (0.3.3). Please give it a try!

**Comment by cddqssc** [comment]
> 

Works perfectly for me, thanks for your effort!
