### ISSUE TITLE
Exceeding maximum token length

### ISSUE THREAD

**Issue by Phr33d0m** [machinewrapped/gpt-subtrans#4]
Hi, thanks for this awesome tool :heart: . I wanted to translate a 4h20min conference and tried to rely on the default values (scene/batch sizes) - but after a while the tool fails with this error stack:

```
WARNING: Hit API token limit, retrying batch without context...
WARNING: Unable to match 2 subtitles with a source line
WARNING: Hit API token limit, retrying batch without context...
WARNING: Hit API token limit, retrying batch without context...
WARNING: Hit API token limit, retrying batch without context...
WARNING: Hit API token limit, retrying batch without context...
WARNING: Hit API token limit, retrying batch without context...
WARNING: Hit API token limit, retrying batch without context...
WARNING: Hit API token limit, retrying batch without context...
WARNING: Unable to match 1 subtitles with a source line
WARNING: Hit API token limit, retrying batch without context...
WARNING: Hit API token limit, retrying batch without context...
WARNING: Hit API token limit, retrying batch without context...
WARNING: Hit API token limit, retrying batch without context...
WARNING: OpenAI error This model's maximum context length is 4097 tokens. However, your messages resulted in 4216 tokens. Please reduce the length of the messages., retrying in 8.0...
WARNING: OpenAI error This model's maximum context length is 4097 tokens. However, your messages resulted in 4216 tokens. Please reduce the length of the messages., retrying in 16.0...
WARNING: OpenAI error This model's maximum context length is 4097 tokens. However, your messages resulted in 4216 tokens. Please reduce the length of the messages., retrying in 32.0...
WARNING: OpenAI error This model's maximum context length is 4097 tokens. However, your messages resulted in 4216 tokens. Please reduce the length of the messages., retrying in 64.0...
WARNING: OpenAI error This model's maximum context length is 4097 tokens. However, your messages resulted in 4216 tokens. Please reduce the length of the messages., retrying in 128.0...
WARNING: OpenAI failure This model's maximum context length is 4097 tokens. However, your messages resulted in 4216 tokens. Please reduce the length of the messages., aborting after 5 retries...
WARNING: Failed to translate all scenes (This model's maximum context length is 4097 tokens. However, your messages resulted in 4216 tokens. Please reduce the length of the messages.)... finishing
WARNING: Failed to translate 1907 subtitles:
```

So I guess it isn't accurately calculating scene/batch sizes?

The command line I used:
```gpt-subtrans.cmd subtitle.srt -l Spanish -o subtitle.es.srt -p True```

**Comment by machinewrapped** [comment]
Hi, thanks for the report! 

The scene/batch calculation uses a very basic heuristic to split subtitles at what seem like plausible breaks - I guess a conference probably doesn't have many obvious "scenes".

The defaults are quite conservative though, to keep ChatGPT's tendency to desync in check, so I'm surprised it hits the token limit. Exactly what constitutes "a token" is somewhat vague though, and the limit applies to (request + response) so there's no way to be sure it won't be hit. I suppose the solution is to split the batch if it hits the token limit, I'll look into that. 

In the meantime you could try tuning these parameters to see if it keeps batches manageable.

`--maxbatchsize`  (default is 25, try 15-20)
`--batchthreshold` (default is 5 (seconds), try 2 or 3)
`--scenethreshold` (default is 30 seconds, try 10 - maybe even less, depending on the speaker(s))

Batching normally only happens the first time an SRT file is processed, it reads the batches from the .subtrans file on subsequent runs. You can delete the project file or add `--project write` to the arguments to rebatch them, but it will restart the translation from the beginning. _Memo to self: add a "rebatch" option that preserves translations._

It might be worth opening the .subtrans file in a text editor to see if something has gone obviously wrong, either in the request or the response... maybe ChatGPT has taken issue with something that was said and gone on a rant :p More likely, the <summary /> tag has grown excessively long, I suspect the instruction to include a "brief summary" is a bit too open to interpretation. You can try tuning the instructions to be better suited to the task.

In _theory_ you could hand-edit the subtrans file to split the problematic batches, but it's likely to break things - better to wait until the GUI is ready, it should make it a lot easier to see where problems are and do something about them.
