### ISSUE TITLE
Intention retranslation in instruction.txt?

### ISSUE THREAD

**Issue by chen-rn** [machinewrapped/gpt-subtrans#41]
I noticed that in instructions.txt, at the end, there is the following line

```
#######################
There was an issue with the previous translation. 

Please translate the subtitles again, paying careful attention to ensure that each line is translated separately, and that every line has a matching translation.

Do not merge lines together in the translation, it leads to incorrect timings and confusion for the reader.
```

is this intentionally left in there?

**Comment by machinewrapped** [comment]
Yes, any instructions after a line of ### are used as the prompt if the translation fails validation - the whole message chain is sent again + this prompt.

It was a quick & dirty solution that I haven't got around to replacing with something more structured yet, but it does the job!

**Comment by chen-rn** [comment]
Ohhh interesting! Gotcha gotcha!
