### ISSUE TITLE
can we make the code simpler 

### ISSUE THREAD

**Issue by iorilu** [machinewrapped/gpt-subtrans#42]
I am looking for a subtitle chatgpt tool

this one seems good , and I tested it for a few srt file

all worked fine , solved that line not match issue for subtitles

but I felt the code is too complicated , too many levels invocation and classes, like some java style

maybe there is some simple way to use a few functions to solve it 

actually I want to copy some code , but don't want to copy all files , seems not east to do it .

**Comment by anilbey** [comment]
A local server to mock openAI may be added for the unit tests.

E.g. the server will respond the same input batch as the output. That would enable unit testing. In presence of the unit tests, refactoring will become easier.

**Comment by anilbey** [comment]
Oh it seems `unittest.mock` can mock HTTP requests. There is no need to write a test server.

https://stackoverflow.com/a/28507806/1935611

**Comment by zh-plus** [comment]
I have integrated the translation process into my project, making it more concise and better abstracted. You can refer to 
https://github.com/zh-plus/Open-Lyrics/blob/master/openlrc/translate.py#L74

Also, I agree with anilbey
> A local server to mock openAI may be added for the unit tests.
> 
> E.g. the server will respond the same input batch as the output. That would enable unit testing. In presence of the unit tests, refactoring will become easier.

**Comment by machinewrapped** [comment]
Would love some volunteers for this :)

**Comment by machinewrapped** [comment]
Closing this as an old issue, whilst acknowledging that unit tests would still be a good idea.
