### ISSUE TITLE
Create Discord Server?!

### ISSUE THREAD

**Issue by chen-rn** [machinewrapped/gpt-subtrans#46]
I have some stuff that I'd love to discuss but it feels like a waste of an issue haha.

@machinewrapped Do you want to create a Discord channel for less significant + faster dicussions revolving this library or simply using GPT/LLMs to translate subtitles?

**Comment by machinewrapped** [comment]
Let's try this!

**Comment by machinewrapped** [comment]
Let's try this: https://github.com/machinewrapped/gpt-subtrans/discussions

**Comment by chen-rn** [comment]
sounds good!
