### ISSUE TITLE
Allow configuration of API base address.

### ISSUE THREAD

**Issue by cddqssc** [machinewrapped/gpt-subtrans#48]
Nice application, would be even better if we could configure the API base address(default: https://api.openai.com/v1).

![image](https://github.com/machinewrapped/gpt-subtrans/assets/31430047/20caec39-a270-4c1d-a179-24b410ce0ce2)

**Comment by machinewrapped** [comment]
Looks like it should be straightforward - what difference does the base address make?

If you have the ability to add the option yourself, please go ahead and make a pull request :-)

**Comment by cddqssc** [comment]
This is indeed a very niche requirement, perhaps only I will use it... I will make the modifications locally

**Comment by machinewrapped** [comment]
Please do create a PR if you get it working - you're the second person to request it so I guess others would use it, and I've no idea how to test it if I do it myself :-)

**Comment by cddqssc** [comment]
Fine, let me do this

**Comment by cddqssc** [comment]
Please check:
https://github.com/machinewrapped/gpt-subtrans/pull/50

**Comment by machinewrapped** [comment]
It's merged - thanks! It will be in the next release.
