### ISSUE TITLE
Request versions

### ISSUE THREAD

**Issue by RistoRoosipuu** [machinewrapped/gpt-subtrans#53]
Which version of requests is required for 3.0?

Been having difficulty getting it to run.

requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.1.0)/charset_normalizer (2.0.7) doesn't match a supported version!

I've tried downgrading by hand but no luck so far.

**Comment by machinewrapped** [comment]
Oh, yeah... that's my fault! New version incoming :)

**Comment by machinewrapped** [comment]
Please try version 0.3.2, let me know if you're still having trouble.

**Comment by RistoRoosipuu** [comment]
Works perfectly now.

Thanks. Closing issue.
