### ISSUE TITLE
Modify project options are not written to `*.subtrans` when opening a new subtitle

### ISSUE THREAD

**Issue by AChangAZha** [machinewrapped/gpt-subtrans#56]
When creating a new project, `datamodel.options` and `project.options` are the same object.
https://github.com/machinewrapped/gpt-subtrans/blob/d8f657024e8095377c523211b92a466e1aabfc00/GUI/ProjectCommands.py#L35
After modifying the project options, `datamodel.options` (actually `project.options`) will trigger an update.
https://github.com/machinewrapped/gpt-subtrans/blob/d8f657024e8095377c523211b92a466e1aabfc00/GUI/MainWindow.py#L228
Then execute `project.UpdateProjectOptions()`. The following conditions are always True, the method will return and `WriteProjectFile()` will not be called.
https://github.com/machinewrapped/gpt-subtrans/blob/d8f657024e8095377c523211b92a466e1aabfc00/PySubtitleGPT/SubtitleProject.py#L275

**Comment by machinewrapped** [comment]
Ah! Does that result in the movie name/description/etc disappearing if you reload without saving? I've seen it happen but hadn't worked out exactly when.

**Comment by AChangAZha** [comment]
Sorry, I don't quite understand what you mean.
When you open a new `.srt` file, but there is no corresponding `.subtrans` for this file, then when you modify name/description/etc, and the input box loses focus, it should save the changes to `.subtrans` and log box below should output:
```
Writing project data to...
```
But that didn't happen. Even hitting the save button doesn't help.
Re-open the `.srt` file, then detect the corresponding `.subtrans`, everything will be normal.
In fact, this problem does not affect the translation. All options are valid, but they will not be written into `.subtrans`. After the translation is completed, `WriteProjectFile()` will be triggered.
Just a little bug. :-)

**Comment by machinewrapped** [comment]
Fixed in v0.3.3... hopefully without introducing _too_ many new bugs!

**Comment by AChangAZha** [comment]
Thanks!&nbsp;

--------------原始邮件--------------
发件人："machinewrapped ***@***.***&gt;;
发送时间：2023年7月22日(星期六) 晚上9:34
收件人："machinewrapped/gpt-subtrans" ***@***.***&gt;;
抄送："张瀚 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [machinewrapped/gpt-subtrans] Modify project options are not written to `*.subtrans` when opening a new subtitle (Issue #56)
-----------------------------------

 

 
Fixed in v0.3.3... hopefully without introducing too many new bugs!
