### ISSUE TITLE
MacOS Intel CPU GUI version runs error

### ISSUE THREAD

**Issue by neohob** [machinewrapped/gpt-subtrans#58]
got error message: bad CPU type in executable

**Comment by machinewrapped** [comment]
Ah, my Mac Mini is an M2, I guess the packaged version is CPU specific. It looks like it is possible to build a universal package, I'll investigate further and see what I can do.

**Comment by machinewrapped** [comment]
OK, if I got this right, v0.3.3 should be a universal binary:
https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.3.3

Can you check it and see if it works for you?

**Comment by neohob** [comment]
> OK, if I got this right, v0.3.3 should be a universal binary: https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.3.3
> 
> Can you check it and see if it works for you?

It's working well, thanks

**Comment by machinewrapped** [comment]
Great!
