### ISSUE TITLE
intel cpu MacOS, v0.3.3 crash

### ISSUE THREAD

**Issue by neohob** [machinewrapped/gpt-subtrans#62]
INFO: Starting single threaded translation
INFO: Translating scene number 1
WARNING: Unable to match 30 lines with a source line
WARNING: Scene 1 batch 1 failed validation, requesting retranslation
INFO: error_code=None error_message="Invalid value for 'content': expected a string, got null." error_param=messages.[5].content error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[1]    38127 segmentation fault  /Users/xxx/gui-subtrans/gui-subtrans

Saving session...completed.

**Comment by machinewrapped** [comment]
Thanks - looks like a problem with the translation request, would you be able to provide the source subtitles so I can see if I can reproduce it?

**Comment by neohob** [comment]
same subtitle file on v0.3.2 works fine

**Comment by machinewrapped** [comment]
I think you can attach it here, but you can email it to machinewrapped at gmail dot com if you'd prefer.

If you're able to install the app from source it should fetch appropriate libraries for your CPU/OS combination, so that might be a solution. https://github.com/machinewrapped/gpt-subtrans#installation

**Comment by neohob** [comment]
Yes, I installed it using the git method and it works fine. There are some issues when using the GUI though.

**Comment by machinewrapped** [comment]
Thanks for providing the subtitles. They work fine for me on the M2 Mac, I've tried updating the script that builds the installer to force it to use universal binaries, but it reports an error with PySide6 (the GUI framework). Please let me know if v0.3.4 works OK on Intel.

**Comment by neohob** [comment]
0.3.4  tested, 

Thank you for your correction, but there are still errors. There seems to be an issue in the log as only 40 out of 100 sentences have been translated in 1-GPT.srt

--------

Sunday, 21:58:25 - Unable to match 30 lines with a source line
Sunday, 21:58:25 - Scene 1 batch 1 failed validation, requesting retranslation
Sunday, 21:58:38 - Retranslation request did not produce a useful result
Sunday, 21:58:38 - Retranslation request did not fix problems:
#1
(Transporting in the mountains) Basically, nothing is easy.

#2
There are no easy parts.

#3
The blades are getting longer.

#4
If you can't transport it, someone else can.

#5
I want to become that "someone else".

#6
97 meters is taller than a 30-story building.

#7
These blades are of this length.

#8
Zhang Jun and his blade transport team.

#9
It's their first time transporting as well.

#10
Just two months ago, the blades they transported were only around 80 meters.

#11
The pace of advancement is too fast.

#12
The blades are getting longer.

#13
The blades are getting longer.

#14
The longer the blades, the larger the swept area.

#15
And the larger the swept area, the greater the power generation.

#16
And this also means.

#17
Transporting these mammoth "bodyguards".

#18
There are more obstacles to overcome on the road and the difficulty is greater.

#19
They are suspended in the air, over 90 meters high.

#20
If the front moves even a meter.

#21
It means the direction has slightly shifted.

#22
The back can move (sway) by seven or eight meters.

#23
If it encounters rocks.

#24
It becomes a hole.

#25
There's a possibility it will be scrapped.

#26
The destination for this transport.

#27
Is on a mountain ridge to the west of Guihuaquan Town, Chongyang County, Hubei Province.

#28
The convoy needs to transport 6 sets of 18 blades.

#29
From the county's storage yard to the mountaintop wind farm.

Sunday, 21:58:38 - Scene 1 batch 1: 0 lines and 30 untranslated.
Sunday, 21:59:07 - Scene 1 batch 2: 30 lines and 0 untranslated.
Sunday, 21:59:36 - Unable to match 30 lines with a source line
Sunday, 21:59:36 - Scene 1 batch 3 failed validation, requesting retranslation
Sunday, 22:00:07 - Retranslation request did not produce a useful result
Sunday, 22:00:07 - Retranslation request did not fix problems:
Apologies for the oversight. Here are revised translations for the missing lines:

#61
Original: 前面等一下等一下
Translation: Wait a moment up front

#62
Original: 稍微摆（矮）一点点
Translation: Lower it a bit, just a little

#63
Original: 好的 知道知道
Translation: Okay, understood, understood

#64
Original: 走走走
Translation: Let's go, go, go

#65
Original: 都是有着15年以上
Translation: All of them have over 15 years

#66
Original: 大货车驾龄的“老司机”
Translation: "Veteran drivers" with extensive truck driving experience

#67
Original: 但每一次运送叶片
Translation: But every time they transport the blades

#68
Original: 他们还是会把心提到嗓子眼
Translation: They still keep their hearts in their mouths

#69
Original: 这个就不能走快
Translation: We can't go fast for this one

#70
Original: 走快后面的工装（手）操作不及
Translation: If we go fast, the crane operator in the back won't be able to keep up

#71
Original: 中间在这个阶段
Translation: In the middle of this stage

#72
Original: 如果说你要是踩了刹车
Translation: If you step on the brakes

#73
Original: 叶片举得高的话
Translation: If the blades are held too high

#74
Original: 叶片的上下有个颤动
Translation: The blades will have some vibration

#75
Original: 就一定有风险了
Translation: Then there will definitely be risks

#76
Original: 闪转腾挪
Translation: Maneuvering and dodging

#77
Original: 所有人都紧盯着这个庞然大物
Translation: Everyone is closely watching this colossal object

#78
Original: 车队用近乎步行的速度缓慢前行
Translation: The convoy moves slowly at a walking pace

#79
Original: 八个小时后
Translation: After eight hours

#80
Original: 终于挪到了山脚下
Translation: Finally moved to the foot of the mountain

#81
Original: 此时真正的挑战才刚刚开始
Translation: The real challenge is just beginning now

#82
Original: (叶片)30吨左右
Translation: (Blades) weighing around 30 tons

#83
Original: 重量全部在空中
Translation: The entire weight is in the air

#84
Original: 把你的车子往后拽往后拉
Translation: Pull your vehicle back, backward

#85
Original: 举得太高
Translation: Holding it too high

#86
Original: 你看叶片它有100米长在空中转
Translation: Look, the blade is about 100 meters long, spinning in the air

#87
Original: 还要避开所有的障碍
Translation: Also need to avoid all obstacles

#88
Original: 所以你这个车子就爬不动
Translation: So your vehicle won't be able to climb

#89
Original: 必须要装载机牵引
Translation: We must use a loader for towing

#90
Original: 体型巨大受力面积庞大
Translation: It's huge in size with a large area to bear force

Sunday, 22:00:07 - Scene 1 batch 3: 0 lines and 30 untranslated.
Sunday, 22:00:12 - Scene 1 batch 4: 10 lines and 0 untranslated.
Sunday, 22:00:12 - Saving translation to /Users/xxx/Downloads/sub/1-GPT.srt
Sunday, 22:00:12 - Writing project data to /Users/xxx/Downloads/sub/1.subtrans

**Comment by machinewrapped** [comment]
That's weird. The first batch that failed returned completely the wrong format, it's dropped the Original> and Translation> markers. The translation itself seems fine, apart from that,  so I can maybe add a fallback case to handle that.

Batch 3 is weird... it's replaced ">" with ":", I haven't seen it do that before. I guess I can add a fallback to cover that case too, though there's a risk it will match against actual subtitle content.

Here's what I get when I try it:
[1.zip](https://github.com/machinewrapped/gpt-subtrans/files/12335638/1.zip)

**Comment by machinewrapped** [comment]
Finally reproduced the "Invalid value for 'content': expected a string, got null" error and have added a fix in 0.4.2. I also added fallback patterns that should catch both the incorrect response formats you had here.

As a side note, for files this small you'd probably be better off using the turbo-16k GPT model and translating the whole thing in one batch!
