### ISSUE TITLE
Freezes with no error message. how configure logging?

### ISSUE THREAD

**Issue by romanr** [machinewrapped/gpt-subtrans#76]
```
INFO: Starting single threaded translation
INFO: Translating scene number 1
INFO: Scene 1 batch 1: 23 lines and 0 untranslated.
INFO: Scene 1 batch 2: 8 lines and 0 untranslated.
INFO: Scene 1 batch 3: 11 lines and 0 untranslated.
INFO: Scene 1 batch 4: 26 lines and 0 untranslated.
INFO: Scene 1 batch 5: 7 lines and 0 untranslated.
^C^C
^C^C^C^C
```
Stopped indefinitely. Can not be killed by ,Ctrl-C. only from another shell.

How to configure logging to see what's wrong?

**Comment by machinewrapped** [comment]
Hi, you should be able to enable verbose logging by creating a '.env' file in the same folder as the application and adding the line "LOG_LEVEL=DEBUG" to it. Please let me know if it shows any useful information about what the problem is.
