### ISSUE TITLE
Segment violation after loading the .srt

### ISSUE THREAD

**Issue by numeropi** [machinewrapped/gpt-subtrans#78]
INFO: Loading stylesheet from /home/kapis/Descargas/gpt-subtrans/theme/subtrans.qss
INFO: GPT-Subtrans v0.4.4
INFO: Project file /home/kapis/Videos/www.Torrenting.com   -    Scrapper (2023) 720p WEBRip-LAMA/Scrapper.2023.720p.WEBRip.x264.AAC-LAMA.subtrans does not exist
INFO: Project settings set
INFO: Executing BatchSubtitlesCommand
INFO: Writing project data to /home/kapis/Videos/www.Torrenting.com   -    Scrapper (2023) 720p WEBRip-LAMA/Scrapper.2023.720p.WEBRip.x264.AAC-LAMA.subtrans
INFO: Legalised content '\n' to ''
INFO: Legalised content '\n' to ''
INFO: Legalised content '♪ And I was having fun,\nwe were all having fun ♪\n\n\n' to '♪ And I was having fun,\nwe were all having fun ♪'
Violación de segmento (`core' generado)

I attach the subtitle that was wanted to be translated
[ezyzip.zip](https://github.com/machinewrapped/gpt-subtrans/files/13207062/ezyzip.zip)

**Comment by machinewrapped** [comment]
I can't reproduce the segmentation fault with those subtitles, but I guess it might have something to do with the first two lines, which are invalid. I recommend using Subtitle Edit's Fix Common Errors and Renumber tools on the source file to clean it up (https://github.com/SubtitleEdit/subtitleedit/releases), delete the `.subtrans` file if there is one and try again.
