### ISSUE TITLE
Crashing on .srt files generated by Whisper

### ISSUE THREAD

**Issue by n-endashi** [machinewrapped/gpt-subtrans#91]
This .srt file (renamed to .txt) was created by Whisper running locally on my pc from a presentation I recorded using OBS.  I just upgraded to the lastest release 0.4.7 but it gives errors and crashes before completing.  I've tried with gpt-4 and gpt-3.5 turbo, same result. SRT files I get from movies seem to work but any .srt from Whisper I made myself has lots of errors and crashes before finishing usually.

[2023-11-26 08-18-53.srt.txt](https://github.com/machinewrapped/gpt-subtrans/files/13493299/2023-11-26.08-18-53.srt.txt)

**Comment by machinewrapped** [comment]
I found that the way connection errors should be handled has changed in the latest OpenAI API, it's quite possible it would have crashed if you had encountered any previously. It is hopefully correct in the latest version so please give it a go and see if it helps:

https://github.com/machinewrapped/gpt-subtrans/releases

**Comment by n-endashi** [comment]
I ran the translation again with the updated version and your recommended settings and it made it all the way through with one pass and no crashing.  I would like to understand more about the settings and the ramifications of adjusting each though.

**Comment by machinewrapped** [comment]
That's good to hear.

I've updated the project wiki with sections explaining the significance of most of the settings, and guidelines on what to set them to:
https://github.com/machinewrapped/gpt-subtrans/wiki

This is just what seems to work for me, derived from experimentation, so you might find that you need something a bit different. Hopefully I've explained the rationale behind each setting well enough that you can experiment with purpose!
