### ISSUE TITLE
Add an option to not skip lines

### ISSUE THREAD

**Issue by fenixpsicologia** [machinewrapped/gpt-subtrans#98]
Could there be an option to avoid skipping lines that are overlapping? Since the project doesn't support subtitles in .ASS format, one way to work around this is to convert the subtitle to SRT and then copy the translated lines into the original file (typically using Aegisub scripts like Multicopy).

In ASS subtitles, it's very common to have overlapping dialogues, such as when one character interrupts another, when two characters are speaking simultaneously, or when there are background dialogues.

Example SRT file: https://drive.google.com/file/d/1RHhHQIQDgBzCe87ImihIj2s0UuzXFPYl/view?usp=sharing

```log
Monday, 11:42:23 - GPT-Subtrans v0.5.0
Monday, 11:42:27 - Project file C:\Users\Lucas Mateus\Downloads\overlapping_example.subtrans does not exist
Monday, 11:42:28 - HTTP Request: GET https://api.openai.com/v1/models "HTTP/1.1 200 OK"
Monday, 11:42:34 - Project settings set
Monday, 11:42:34 - Executing BatchSubtitlesCommand
Monday, 11:42:34 - Writing project data to C:\Users\Lucas Mateus\Downloads\overlapping_example.subtrans
Monday, 11:42:36 - Starting single threaded translation
Monday, 11:42:36 - Translating scene number 1
Monday, 11:42:36 - Translating with OpenAI model gpt-3.5-turbo, Using API Base: https://api.openai.com/v1
Monday, 11:42:40 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Monday, 11:42:40 - Scene 1 batch 1: 9 lines and 0 untranslated.
Monday, 11:42:40 - Saving translation to C:\Users\Lucas Mateus\Downloads\overlapping_example-GPT.srt
Monday, 11:42:40 - Skipped subtitle at index 5: Subtitle start time >= end time
Monday, 11:42:40 - Writing project data to C:\Users\Lucas Mateus\Downloads\overlapping_example.subtrans
````

**Comment by fenixpsicologia** [comment]
I managed to solve this manually by changing this option in the SRT library to False.

https://github.com/cdown/srt/blob/develop/srt.py#L256

**Comment by machinewrapped** [comment]
Hi, thanks for looking into this - I wasn't aware it was happening. It looks like specifying `reindex=False` in the calls to `srt.compose` should prevent it. I'll try it next time I'm translating something and change it in the next update if it seems to work.

**Comment by machinewrapped** [comment]
@fenixpsicologia can you try v0.5.1? It no longer reindexes the subtitles when it writes them.

https://github.com/machinewrapped/gpt-subtrans/releases

(Windows only right now, I'll build a Mac package later)

**Comment by fenixpsicologia** [comment]
> @fenixpsicologia can you try v0.5.1 (or v0.5.2)? It no longer reindexes the subtitles when it writes them.
> 
> https://github.com/machinewrapped/gpt-subtrans/releases
> 
> (Windows only right now, I'll build a Mac package later)

It has been resolved, thank you very much.
